AWSTemplateFormatVersion: '2010-09-09'

Description: 'ECS cluster'

Parameters:
  VpcId:
    Description: Id of the vpc to deploy to
    Type: String

  ASGSubnet:
    Description: VPC subnet to put asg in
    Type: String

  ClusterName:
    Description: Name of the cluster to create
    Type: String

  AMI:
    Description: Name of the ami to use
    Type: String
    Default: ami-0bb804e8cd910a664

  InstanceType:
    Description: Instance type that will be used in created cluster
    Type: String
    Default: t2.micro

  KeyName:
    Description: Name of the key pair for accessing machines
    Type: String

  NextcloudBackupBucketName:
    Description: Name of the nextcloud backup bucket
    Type: String

  DbBackupBucketName:
    Description: Name of the db backup bucket
    Type: String

  PrimaryStorageBucketName:
    Description: Name of the primary storage bucket
    Type: String
  Domain:
    Description: Full domain address
    Type: String

Resources:

  NextcloudStorageUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
      - PolicyName: nextcloud-storage-policy
        PolicyDocument:
          Statement:
            - Effect: "Allow"
              Action: "s3:*"
              Resource:
                - !Sub "arn:aws:s3:::${PrimaryStorageBucketName}/*"
                - "arn:aws:s3:::${PrimaryStorageBucketName}"

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName

  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${ClusterName}-security-group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80
          IpProtocol: tcp
        - CidrIp: 0.0.0.0/0
          FromPort: 443
          ToPort: 443
          IpProtocol: tcp
        - FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          IpProtocol: tcp

      Tags:
        - Key: Name
          Value: !Sub ${ClusterName}-security-group

  ECSRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${ClusterName}-ecs-iam-role
      AssumeRolePolicyDocument: |
        {
          "Statement": [{
            "Action": "sts:AssumeRole",
            "Effect": "Allow",
            "Principal": {
              "Service": [
                "ec2.amazonaws.com",
                "ecs.amazonaws.com"
              ]
            }
          }]
        }
      Policies:
      - PolicyName: ecs-service
        PolicyDocument: |
          {
            "Statement": [{
              "Effect": "Allow",
              "Action": [
                "ecs:CreateCluster",
                "ecs:DeregisterContainerInstance",
                "ecs:DiscoverPollEndpoint",
                "ecs:Poll",
                "ecs:RegisterContainerInstance",
                "ecs:StartTelemetrySession",
                "ecs:Submit*",
                "s3:*",
                "ec2:Describe*"
              ],
              "Resource": "*"
            }]
          }

  ECSInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
       - !Ref ECSRole

  ECSAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref ASGSubnet
      LaunchConfigurationName: !Ref ECSLaunchConfiguration
      MinSize: 1
      MaxSize: 1
      DesiredCapacity: 1
      Tags:
        - Key: Name
          Value: !Sub ${ClusterName}-ecs-instance
          PropagateAtLaunch: true
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
    UpdatePolicy:
     AutoScalingRollingUpdate:
        MinInstancesInService: 0
        MaxBatchSize: 1
        PauseTime: PT15M
        SuspendProcesses:
          - HealthCheck
          - ReplaceUnhealthy
          - AZRebalance
          - AlarmNotification
          - ScheduledActions
        WaitOnResourceSignals: true

  ECSLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref AMI
      KeyName: !Ref KeyName
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref ECSSecurityGroup
      IamInstanceProfile: !Ref ECSInstanceProfile
      UserData:
        "Fn::Base64": !Sub |
          #!/bin/bash
          yum install -y aws-cfn-bootstrap
          /opt/aws/bin/cfn-init -v --region ${AWS::Region} --stack ${AWS::StackName} --resource ECSLaunchConfiguration
          /opt/aws/bin/cfn-signal -e $? --region ${AWS::Region} --stack ${AWS::StackName} --resource ECSAutoScalingGroup
    Metadata:
      AWS::CloudFormation::Init:
       config:
          packages:
            yum:
              aws-cli: []
              vim-enhanced: []
          commands:
            01_add_instance_to_cluster:
              command: !Sub echo ECS_CLUSTER=${ECSCluster} >> /etc/ecs/ecs.config
          files:
            "/etc/cfn/cfn-hup.conf":
              mode: '000400'
              owner: root
              group: root
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}

            "/etc/cfn/hooks.d/cfn-auto-reloader.conf":
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.ECSLaunchConfiguration.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --region ${AWS::Region} --stack ${AWS::StackName} --resource ECSLaunchConfiguration

            "/etc/nginx/certificateCreator.conf":
              content: !Sub |
                server {
                  listen 80;
                  server_name ${Domain};

                  location /.well-known {
                    allow all;
                    root  /data/letsencrypt/;
                  }
                }

            "/etc/cron.d/nextcloud-backup":
              mode: "000644"
              owner: root
              group: root
              content: !Sub |
                  0 23 * * * root  sudo tar -czf - /data/nextcloud | aws s3 cp - s3://${NextcloudBackupBucketName}/`date +"%d_%m_%y".tar.gz`
                  0 23 * * * root  docker exec `docker ps | grep "mariadb" | awk '{ print $1 }'` sh -c 'exec mysqldump --all-databases -uroot -p"$MYSQL_ROOT_PASSWORD"' |  aws s3 cp - s3://${DbBackupBucketName}/nextcloud_sqlbkp_`date +"%Y%m%d"`.bak

            "/etc/nginx/conf.d/default.conf":
              content: !Sub |
                server {
                  listen 80;
                  server_name ${Domain};
                  location / {
                    return 301 https://$server_name$request_uri;  # enforce https
                  }
                }

                server {
                  listen 443 ssl;
                  server_name ${Domain};
                  ssl_certificate /etc/letsencrypt/live/${Domain}/fullchain.pem;
                  ssl_certificate_key /etc/letsencrypt/live/${Domain}/privkey.pem;

                  location / {
                    proxy_pass http://nextcloud:80;
                    proxy_set_header Host $host;
                    proxy_set_header X-Forwarded-Host $host;
                    proxy_set_header X-Forwarded-Server $host;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                    # WebSocket support

                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection "upgrade";
                  }
                }

          services:
            sysvinit:
              cfn-hup:
                enabled: true
                ensureRunning: true
                files:
                  - /etc/cfn/cfn-hup.conf
                  - /etc/cfn/hooks.d/cfn-auto-reloader.conf
