AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Project:
    Description: Name of the project for which vpc is created
    Type: String
  VpcId:
    Description: Id of the VPC to deploy db to.
    Type: AWS::EC2::VPC::Id
  Subnets:
    Type: CommaDelimitedList
    Description: Comma-delimited list of subnets that db will be deployed to.
  BackupRetentionPeriod:
    Type: Number
    Description: How long backups should be kept (in days)
  InstanceType:
    Type: String
    Description: Instance type for the machine that will host db
  EngineVersion:
    Type: String
    Description: DB engine version
  Engine:
    Type: String
    Description: Engine to use
  Username:
    Type: String
    Description: Username to use
  AllocatedStorage:
    Type: Number
    Description: Storage in GB
  MasterPassPathSSM:
    Type: String
    Description: SSM path under which master password is set.


Resources:
  DBSubnetGroupName:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: String
      DBSubnetGroupName: !Sub ${Project}-subnet-group
      SubnetIds: !Ref Subnets

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${Project}-sg
      SecurityGroupIngress:
        - FromPort: 5432
          ToPort: 5432
          CidrIp: "0.0.0.0/0"
          IpProtocol: tcp
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub ${Project}-sg

  DB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: !Ref AllocatedStorage
      AutoMinorVersionUpgrade: true
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      DBInstanceClass: !Ref InstanceType
      DBInstanceIdentifier: !Sub '${Project}-db'
      DBSubnetGroupName: !Ref DBSubnetGroupName
      Engine: !Ref Engine
      EngineVersion: !Ref EngineVersion
      MasterUsername: !Ref Username
      MasterUserPassword: !Sub '{{resolve:ssm-secure:${MasterPassPathSSM}:1}}'
      MultiAZ: no
      Port: "5432"
      PreferredBackupWindow: "23:59-00:29"
      PreferredMaintenanceWindow: "Mon:01:59-Mon:02:29"
      PubliclyAccessible: false
      StorageEncrypted: false
      StorageType: gp2
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
